version: '3.7'
services:  
  db:
    image: mysql:5.7
    restart: always
    ports: 
      - "3305:3306"
    environment:
      MYSQL_DATABASE: 'mud_vulcano'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: "Vulcano123?"
    volumes:
      - ./db:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'mimikostapp'
    ports:
      - 8181:80
    volumes:
      - ./:/var/www/html